# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iid', models.CharField(max_length=100, verbose_name='\u4ea7\u54c1\u578b\u53f7')),
                ('name', models.CharField(max_length=100, verbose_name='\u5b9d\u8d1d\u540d\u79f0\uff08\u82f1\uff09')),
                ('imgUrls', models.CharField(max_length=1000, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('category', models.CharField(max_length=1000, verbose_name='\u5206\u7c7b')),
                ('weight', models.CharField(max_length=1000, verbose_name='\u91cd\u91cf\uff08\u78c5\uff09')),
                ('sizes', models.CharField(max_length=1000, verbose_name='\u53ef\u9009\u5c3a\u7801')),
                ('gender', models.CharField(max_length=1000, verbose_name='\u6027\u522b')),
                ('brand', models.CharField(max_length=1000, verbose_name='\u54c1\u724c')),
                ('itemUrl', models.CharField(max_length=1000, verbose_name='\u5b98\u7f51\u5730\u5740')),
                ('price', models.CharField(max_length=1000, verbose_name='\u6d77\u5916\u4ef7\u683c\uff08\u7f8e\u5143\uff09')),
                ('feature', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u82f1\uff09')),
                ('featureTrans', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u7ffb\u8bd1\uff09')),
            ],
            options={
                'verbose_name': '\u5b9d\u8d1d',
                'verbose_name_plural': '\u5b9d\u8d1d\u5217\u8868',
            },
        ),
    ]
